name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-20.04]
        tarantool: ['1.10', '2.4', '2.5', '2.6', '2.7']
    runs-on: ${{ matrix.runs-on }}
    env:
      CMAKE_LDOC_FIND_REQUIRED: 'YES'
    steps:
      - uses: actions/checkout@v2
      - uses: rosik/setup-tarantool@v1
        with:
          tarantool-version: ${{ matrix.tarantool }}

      # Setup luacheck, ldoc and luatest
      - run: tarantoolctl rocks install luacheck
      - run: tarantoolctl rocks install ldoc
          --server=https://tarantool.github.io/LDoc/
      - run: tarantoolctl rocks install luatest 0.5.2
      - run: echo ".rocks/bin" >> $GITHUB_PATH

      - run: tarantoolctl rocks make
      - run: .rocks/bin/luatest -v
      - run: luacheck .
